server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/cliente/**
        - id: servicio-foto
          uri: lb://servicio-foto
          predicates:
            - Path=/fotos/**
        - id: servicio-gateway
          uri: lb://servicio-gateway
          predicates:
            - Path=/**